/*
 * This file is generated by jOOQ.
 */
package com.github.jobjava00.jooq;


import com.github.jobjava00.jooq.tables.Meeting;
import com.github.jobjava00.jooq.tables.Person;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.MEETING</code>.
     */
    public static final Meeting MEETING = com.github.jobjava00.jooq.tables.Meeting.MEETING;

    /**
     * The table <code>PUBLIC.PERSON</code>.
     */
    public static final Person PERSON = com.github.jobjava00.jooq.tables.Person.PERSON;
}
